# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('t_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regex', models.TextField(verbose_name='规则')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('phone', models.IntegerField(verbose_name='电话')),
                ('ip', models.CharField(max_length=64, verbose_name='用户ip')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('Last_login_time', models.DateTimeField(auto_now=True, verbose_name='最后登陆时间')),
            ],
        ),
        migrations.DeleteModel(
            name='MyBlog',
        ),
    ]
